-- GOLD-e AI Agent customer-channel deployment layer
ALTER TABLE ai_agents
    ADD COLUMN IF NOT EXISTS public_key VARCHAR(64) UNIQUE,
    ADD COLUMN IF NOT EXISTS welcome_message TEXT,
    ADD COLUMN IF NOT EXISTS handoff_message TEXT;

CREATE TABLE IF NOT EXISTS ai_agent_channel_connections (
    id UUID PRIMARY KEY,
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    agent_id UUID NOT NULL REFERENCES ai_agents(id) ON DELETE CASCADE,
    channel VARCHAR(32) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    external_account_id VARCHAR(255),
    external_sender_id VARCHAR(255),
    display_name VARCHAR(255),
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    secret_ciphertext TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(workspace_id, agent_id, channel, provider, external_account_id)
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_channel_workspace
    ON ai_agent_channel_connections(workspace_id, channel, status);

CREATE INDEX IF NOT EXISTS idx_ai_agent_channel_external
    ON ai_agent_channel_connections(channel, external_account_id, external_sender_id);

CREATE INDEX IF NOT EXISTS idx_ai_agents_public_key
    ON ai_agents(public_key);

-- Public deployment keys are generated by the API. Existing agents remain private
-- until the owner explicitly enables a channel.
